# This workflow will run tests using node
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: build

on:
  push:
    branches: ["main"]
  # Runs on any open or reopened pull request
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
